version: 3.3.20.{build}

build:
  parallel: true
  project: Asn1.sln
  verbosity: normal

before_build:
  - setx PATH "%PATH%;c:\cygwin64\bin;c:\Python36-x64"
  - echo %PATH%
  - copy c:\Python36-x64\python.exe c:\Python36-x64\python3.exe 
  - cd Tests
  - make

