version: 3.3.20.{build}

build:
  parallel: true
  project: Asn1.sln
  verbosity: normal

before_build:
#  - appveyor-build.bat
  - doskey make="c:\cygwin64\bin\make.exe"
  - doskey python3="c:\Python36-x64\python.exe"
  - doskey dafuq=dir
  - dafuq
  - cd Tests
  - make

